version: "3"
services:
  client:
    container_name: client
    build:
      context: /root/MERN-CRUD/client/
      dockerfile: Dockerfile
    # Permission
    #command: "chown -R www-data:www-data /usr/local/apache2/htdocs && chmod -R 755 /usr/local/apache2/htdocs"
    volumes:
      - "/root/MERN-CRUD/client:/mnt/client"
    ports:
      - 3000:3000

  server:
    container_name: server
    build:
      context: /root/MERN-CRUD/server/
      dockerfile: Dockerfile
      # Permission
      #command: "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html"  
    volumes:
      - "/root/MERN-CRUD/server:/mnt/server"
    ports:
      - 8080:8080

  database:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: mydata
      MONGO_INITDB_ROOT_USERNAME: mitthu
      MONGO_INITDB_ROOT_PASSWORD: mitthu123
  
      #Permission
      #command: "chown -R www-data:www-data /var/www/html && chmod -R 755 /docker-entrypoint-initdb.d"  
    volumes:
      - "/root/MERN-CRUD:/mnt"
    ports:
      - 27017:27017

  

        
        #network
        
  

    
